### ISSUE TITLE
Add an true/false "alcohol" field for restaurants 

### ISSUE THREAD

**Issue by jaimelightfoot** [citizenlabsgr/beercityfood#11]
yaml format:  
`alcohol: true #or false`

HTML format:  
`<div class="...">🍻Includes alcoholic beverages</div>`

**Comment by twodarek** [comment]
Is this what you were thinking of #14 ?  It adds the beverage display in the delivery-options div (so not named quite right anymore), but it looks like I'd expect from a user perspective.

**Comment by twodarek** [comment]
New commit cleans it up a bit.  🙂
