### ISSUE TITLE
Add a license

### ISSUE THREAD

**Issue by jacebrowning** [citizenlabsgr/beercityfood#7]

**Comment by jaimelightfoot** [comment]
There's a license in the `themes/startpage-theme` directory, should we move it up to the top level?

**Comment by jacebrowning** [comment]
I'm tempted to use MIT similar to our main site: https://github.com/citizenlabsgr/website/blob/master/LICENSE.md

How do you think this content should be licensed?

**Comment by jaimelightfoot** [comment]
Sounds good to me.
